### ISSUE TITLE
Brilliant solution, but LCO files are not taken into account

### ISSUE THREAD

**Issue by gnipp** [weinbusch/django-tex#18]
In core.py in the run_tex, a temp dir is created and passed to run_tex_in_directory.
This prevents the use of KOMA-script as the LCO file(s) are not copied to the temp folder and therefore it leads to an error message accordingly:

TexError at /events/latex
! Package scrletter Error: Letter-Class-Option file `brief-absender.lco' not found.

Anything I didn't understand?

**Comment by weinbusch** [comment]
I have little (meaning no) experience with lco files. If you usually keep them in the same directory as the .tex source file, this won't work with the default `django-tex` configuration, because `run_tex` creates the .tex file in a temporary directory. No additional files are copied to the tempdir. 

However, you might want to use  `run_tex_in_directory`, which allows you to supply the name of a directory that you control. You could, for example, write a function that creates a temporary directory, moves some .lco files in there, calls `run_tex_in_directory`, and the cleans the temporary directory after everything is done. It's a bit fiddly, I think.

A probably better alternative would be to place the .lco files in some central directory (/usr/local/texmf/ or something), where `pdflatex` can see it. This depends on the configuration of your latex installation and is totally independent from the django app. Maybe you can configure your latex installation so that it sees the files in your django project directory...

**Comment by gnipp** [comment]
Please excuse my late response. I'm currently working on my solution into which I'd like to incorporate the django-tex app.

You're right, the problem is the temp copy approach. Is there any particular reason for copying the file into a temp location? I'm just wondering, it will never be modified by the compiler? And having the LCOs aside is quite convenient as you may "outsource" all the variable stuff. They are appended in the header by just providing their name. Like:
`\documentclass[fontsize=11pt,enlargefirstpage=off,firstLCO,secondLCO]{scrlttr2}`

Could be more than one LCO, which gives more flexibility. Examples: Writing a business letter needs to have another bank-account mentioned than a letter for someone else. And if it becomes privately, you probably might not mention your bank-account at all. (unless writing your boy-friend :)

Another case is the signature, which might come from a placed image when you're faxing the document (this dammed last century technique still exists).

Apart from the LCOs, there are also *.adr files containing addresses for serial letters, bib-files etc.

My humble opinion is to reconsider the concept of copying the files to another place.

Kind regards,
Gerald

**Comment by weinbusch** [comment]
Writing the tex file to a temp directory was introduced here: 4dc19abee723375b12f1adf3e270a09d80251528

The reason was that it enables the use of `latexmk`, which was not possible by the former method of feeding the rendered tex code as a string to `Popen.communicate`. 

I think we should definitely keep support for `latexmk`, and I cannot think of another way to make it work. However, I do not know a lot about how `latexmk` works internally other than that it is a perl script.

As to the lco files, you might take a look here: https://tex.stackexchange.com/a/81779

It seems that you can place the lco files in a different directory than the tex source file, but the tex installation needs to be configured to search in this different directory. I guess the same applies to bib files.

As a side note: since you're using django, you might store any address information in your database and feed it to the tex file through the `context` variable when rendering the template, like this: `\setkomavar{fromname}{ {{- your_name -}} }`.  In this case, the database replaces your lco files altogether.

**Comment by JensTimmerman** [comment]
Has anything been done regarding this TEXINPUTS environment variable? I'm having the same issue with fonts.

In my normal flow I just include custom fonts (otf files) in the same directory as the tex file and use ` \setsansfont[Ligatures=TeX,Color=sonicsilver]{HalyardTextBook.otf}`

I also have this problem for includes. e.g. I include all my styling information in a file caled styles.tex and all my macro's in a file called macros.tex and use `\include{styles}`


This normally works. But not in the copy to temp dir workflow used here. having the option of setting TEXINPUTS to the templates dir would probably solve this?
