### ISSUE TITLE
Using a GenericView

### ISSUE THREAD

**Issue by AnasGhrab** [weinbusch/django-tex#22]
Hi,

Is it possible to use django-tex with a generic view (ListView or DetailView) ?

Thanks !

**Comment by weinbusch** [comment]
Hi there, 

yes you can. You would need to subclass the generic view of your choice and modify the `render_to_response` method so that it calls the `compile_template_to_pdf` function. I assume you are aware of this very helpful webpage: [http://ccbv.co.uk/](http://ccbv.co.uk/), because otherwise, subclassing generic views is bad for your mental health.
