### ISSUE TITLE
Ways to build tex file multiple times to get proper cross references, citations, etc.

### ISSUE THREAD

**Issue by partofthething** [weinbusch/django-tex#3]
I am using this library to build a TeX file using `pdflatex` and it nominally works fine, but whereas I typically run `pdflatex` and `bibtex` and then `pdflatex` twice more to get all the cross-references and page numbers right, this only runs it once, leaving a bunch of `?`'s in the document. 

I've explored a few solutions: 
* Have `run_tex` loop twice in the `tempdir` and just run the `latex_command` twice. This works. 
* Use `latexmk` as the `LATEX_INTERPRETER`, which is intended to solve this problem. I had to adjust the way command line arguments get passed to the `process` to get this to work (I needed to also pass the `-pdf` argument through to it) but even then it was no good because it cannot accept input from `stdin` as is done in `run_tex`. I could have written a temporary input file instead of used the stream and that probably would have worked. 

I can make a PR for this but wondered if anyone had a preference on solution before I did.

**Comment by weinbusch** [comment]
Because `latexmk` exists and has the features you want, I'd go for the second option. Please take a look at pull request #4 for a possible solution.

For the first option, it would be interesting to implement a way of looking at the log file and continue calling `latex`, if the log file says it's necessary.
